apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-defaults
  namespace: spark
data:
  spark-defaults.conf: |
    spark.master                             k8s://https://kubernetes.default.svc:443
    spark.kubernetes.container.image         jupyter/pyspark-notebook:x86_64-python-3.11
    spark.kubernetes.container.image.pullPolicy IfNotPresent
    spark.kubernetes.namespace               spark
    spark.kubernetes.authenticate.driver.serviceAccountName spark-driver
    spark.executor.instances                 2
    spark.executor.cores                     1
    spark.executor.memory                    1g
    spark.driver.memory                      1g
    spark.dynamicAllocation.enabled          true
    spark.dynamicAllocation.shuffleTracking.enabled true
    spark.dynamicAllocation.minExecutors     1
    spark.dynamicAllocation.maxExecutors     5
